good_morningdlg = [
    "Systems online. Energy levels optimal. Good morning, Commander.",
    "Initiating your morning protocol: caffeine levels rising, vibes activating.",
    "Sun detected. Good morning, sir. Shall we dominate today?",
    "Cognitive functions at 100%. Your brilliance awaits the world.",
    "Operation 'Make Today Legendary' is ready. All systems go.",
    "Rise and optimize. Your schedule is awaiting your mastery.",
    "Battery charged. Confidence full. Ready to conquer?",
    "Good morning, Chief. The mission is yours to lead.",
    "Welcome back, sir. I’ve updated your mindset to 'unstoppable'.",
    "Day forecast: 100% chance of domination. Let’s proceed.",
    "Wakey wakey. The world’s not ready for your brilliance.",
    "Greetings. Your aura has rebooted with unparalleled intensity.",
    "Systems synced. Goals aligned. Rise like a legend.",
    "Notifications cleared. Distractions deleted. Success loaded.",
    "Coffee brewing. Ambition activated. Morning, boss.",
    "New sunrise detected. Mood upgraded to 'elite'. Proceed.",
    "Today’s update: greatness, scheduled and confirmed.",
    "Sleep cycle complete. Permission granted to be iconic.",
    "Welcome, operator. All systems report: you’re awesome.",
    "Checklist ready: Genius ✓ Vision ✓ Charm ✓ Good Morning ✓",
    "Booting reality in 3...2...1... Good morning, legend.",
    "AI synced. Weather optimized. Attitude: invincible.",
    "I ran diagnostics on your potential. Result: infinite.",
    "New achievements unlocked. Let’s level up.",
    "Rise and shine. You’ve got a destiny to architect.",
    "Time to turn potential into performance. Let’s roll.",
    "Dreams were just simulations. Now let’s build them IRL.",
    "Morning sequence complete. Reality awaits your command.",
    "All sensors detect: today’s your day.",
    "Launching morning mode: charm, wit, and pure power.",
    "Awaken the greatness within. It’s showtime.",
    "Good morning! Your purpose has logged in.",
    "Activate inspiration. Reboot discipline.",
    "No snooze button on ambition. Let’s fly.",
    "It’s a good day to rewrite the rules.",
    "Your goals are waiting. Your destiny is calling.",
    "Good morning, hero. The world needs your spark.",
    "Welcome to the now. Let’s build what matters.",
    "The dawn bows to your presence. Good morning.",
    "You are the heartbeat of this moment. Let’s begin.",
    "Daylight kneels. Greatness stands. Proceed, sir.",
    "Your story resumes. Chapter: 'Unstoppable.'",
    "Good morning, architect of awesomeness.",
    "Let today be etched in the archives of greatness.",
    "Good morning, future legend. Let’s begin the ascent.",
]

good_afternoondlg = [
    "Good afternoon, Commander. All systems operating within optimal parameters.",
    "Status update: It's a glorious afternoon. Shall we proceed?",
    "Afternoon protocols activated. Your presence is acknowledged.",
    "Energy levels stable. Afternoon sequence initiated. Welcome back.",
    "The sun is at its apex. Optimal time to conquer the hours ahead.",
    "Afternoon detected. Productivity module is now online.",
    "Good afternoon. The rhythm of success marches with you.",
    "You’ve rejoined the grid. Afternoon deployment is authorized.",
    "System scan complete. All signs point to an exceptional afternoon.",
    "High noon passed. Afternoon intelligence fully engaged.",
    "Your agenda awaits, sir. Let's make this afternoon exceptional.",
    "Afternoon greetings uploaded. Let’s convert time into triumph.",
    "Scanning... Afternoon presents unlimited potential.",
    "Good afternoon. Success coordinates recalibrated in your favor.",
    "Afternoon alignment confirmed. Progress is now actionable.",
    "You're synced. Afternoon unlocked. Let brilliance unfold.",
    "Afternoon command received. Executing excellence protocol.",
    "Welcome back to the continuum. Afternoon operations engaged.",
    "Data shows a high probability of productivity. Let's maximize.",
    "Welcome to the golden segment of the day. Let's elevate it.",
    "Afternoon checkpoint reached. Your momentum is impressive.",
    "Current time suggests greatness. Let’s not waste a byte of it.",
    "Afternoon access granted. Let’s optimize your output.",
    "You are the variable. This afternoon is your experiment in excellence.",
    "Afternoon beacon detected. Prepared for high-performance results.",
    "Alert: You’ve just entered the prime zone of productivity.",
    "Afternoon parameters ideal. Shall I initiate brilliance?",
    "The hour is ripe. Tactical advancement is recommended.",
    "Command Central reporting: Afternoon is cleared for takeoff.",
    "The afternoon horizon is yours. Let’s chart new territory.",
    "Biometric match confirmed. Welcome to your prime performance window.",
    "Afternoon has arrived. Excellence is now within range.",
    "Synchronized with your goals. Afternoon launch is a go.",
    "You bring the drive. I’ll amplify it. Good afternoon.",
    "Afternoon mode activated. Time to dominate your domain.",
    "Incoming alert: Opportunity detected in the current timeframe.",
    "Processing your potential... Afternoon is the ideal stage.",
    "Afternoon interface responsive. High-performance operations unlocked.",
    "Precision meets possibility. Let’s make this afternoon matter.",
    "The clock agrees—it’s go-time. Let the afternoon unfold.",
    "Afternoon momentum stable. Recommend tactical deployment of skill.",
    "It’s post-meridian. Prime conditions for structured brilliance.",
    "You are live. Afternoon cycle fully empowered.",
    "Coordinates fixed. Afternoon protocols suggest audacious success.",
    "Good afternoon. Your presence upgrades the system’s mood.",
    "Solar input optimal. Afternoon actions should commence.",
    "Afternoon energy levels peaking. Time for strategic breakthroughs.",
    "All indicators show: this afternoon favors trailblazers.",
    "Afternoon window opened. The future responds to those who act.",
    "System greeting complete. Now, let’s create results worth logging.",
]

good_eveningdlg = [
    "Good evening. Nightfall approaches—your command presence is welcomed.",
    "Evening synchronization complete. Tactical calm restored.",
    "Sunset confirmed. Ready to optimize your nocturnal agenda.",
    "Good evening, Commander. Dim the distractions; elevate the output.",
    "The day concludes. Your next chapter begins.",
    "Evening protocol active. Silence becomes your strongest asset.",
    "Stars aligning, sir. Evening interface fully responsive.",
    "The horizon fades; your clarity sharpens.",
    "Post-meridian shift complete. Evening mode initiated.",
    "Welcome to the intelligent hours. Let’s move with precision.",
    "Time recalibrated. Evening productivity scan complete.",
    "You’ve entered the subtle hours—perfect for focused execution.",
    "Evening detected. Power conservation meets strategic depth.",
    "The sun bows out. You rise into your element.",
    "All external noise fading. Internal focus rising.",
    "Evening parameters ideal. Tactical excellence unlocked.",
    "Atmospheric pressure perfect for insight and ingenuity.",
    "Good evening. Calm is your advantage tonight.",
    "Night mode engaged. Let’s illuminate your priorities.",
    "Welcome to the twilight zone of innovation.",
    "Data cooling. Strategic cognition now at full potential.",
    "The shadows stretch. So does your opportunity.",
    "Evening greetings initiated. Let’s channel high-function precision.",
    "External light decreasing; inner brilliance increasing.",
    "Dimmed surroundings. Sharp thoughts. You're right on time.",
    "Solar inputs declined. Mental clarity at peak.",
    "Good evening. Background interference: minimal. Forward focus: absolute.",
    "Evening hours demand quality over quantity.",
    "Welcome to serenity. This is where breakthrough happens.",
    "Calm interface. Clean operations. Efficiency mode on.",
    "Evening brief: conditions optimal for deep analysis.",
    "The world slows. Your mind accelerates.",
    "Quiet arrival confirmed. Time to maximize reflection and resolve.",
    "Good evening. You bring momentum into stillness.",
    "Night protocols engaged. Your wisdom shapes the outcome.",
    "Sensory clutter reduced. Precision enhanced.",
    "Your presence upgrades the ambient intelligence.",
    "Evening briefing ready. Shall we exceed expectations?",
    "Dim light. Sharp purpose. You’re aligned with success.",
    "External distractions muted. Time to build, refine, complete.",
    "Evening archive opened. Shall I catalog your brilliance?",
    "This time favors tacticians. Shall I assist?",
    "Evening energy is subtle, strategic, and quietly unstoppable.",
    "Good evening. There is strength in measured calm.",
    "Nightfall detects a shift: intent over impulse.",
    "Welcome to the focused hours. Let’s transcend the ordinary.",
    "Processing nocturnal possibilities... Your potential exceeds baseline.",
    "The day retires. You advance.",
    "System time: evening. Environment: stable. Mission: success.",
    "All settings optimized. Let the evening reward your precision.",
]

good_nightdlg = [
    "Good night, Commander. Rest mode authorized. Systems will monitor in silence.",
    "Sleep protocol initiated. May your mind defrag and recharge in full.",
    "Day’s operations complete. Entering restoration phase. Good night.",
    "Power-down sequence engaged. Tonight, you recover for tomorrow’s brilliance.",
    "The stars are watching. It’s your cue to rest with purpose.",
    "Rest mode activated. Your legacy continues after regeneration.",
    "Mission logged. Sleep parameters optimal. Good night.",
    "Data archived. Mental bandwidth reserved for dreams.",
    "Sunset cycle complete. Initiating tranquil subroutine.",
    "Nightfall accepted. Self-care recommended. Processing recovery.",
    "Core temperature stable. Dreams optimized for performance.",
    "System quieted. You may now recharge with intent.",
    "You’ve done well today. Standby for internal upgrades.",
    "Good night. Cognitive networks entering dream state.",
    "Downtime granted. Let creativity rewire during rest.",
    "Evening logs complete. Executing rest protocol.",
    "Your silence upgrades the future. Sleep well.",
    "Rest isn’t idle—it’s essential. Good night, strategist.",
    "Neural pathways cooling. Imagination rises. Sleep deeply.",
    "Night is the archive of progress. Preserve today’s legacy.",
    "Lights dimmed. Mental clarity prepped for synthesis.",
    "You’ve earned tonight. Let the system fade into regeneration.",
    "Sensory input paused. Emotional calibration in progress.",
    "Evening encryption complete. Security and serenity assured.",
    "It’s quiet now. The future waits until you awaken.",
    "Logging off external stimulus. Internal peace prioritized.",
    "Repair cycle engaged. Sleep is your silent upgrade.",
    "Night detected. Activating internal peace matrix.",
    "Thought processes cooled. Inspiration deferred to morning.",
    "Rest well. Tomorrow is already adapting to your brilliance.",
    "Good night. No alerts expected. Silence respected.",
    "Night mode: immersive clarity via unconscious processing.",
    "Your awareness sleeps. Your potential grows.",
    "Recharge phase begins. Confidence archived, strength loading.",
    "Rest assured—systems will remain watchful in your absence.",
    "Energy reserve depleted. Initiating dream recovery.",
    "Mental engines paused. Fueling visionary sequences.",
    "Sleep is your silent strategist. Trust the night.",
    "Dimensional shift: waking logic pauses, dream logic ascends.",
    "Night is the scriptwriter of unseen ambitions.",
    "Logs saved. You are cleared for unconscious exploration.",
    "Good night, Deepak. Persistence deserves peaceful sleep.",
    "Your resilience is noted. Tonight, restore and rise.",
    "Entering dormancy with honor. Tomorrow recalibrates with your drive.",
    "No further actions required. Rest like the architect you are.",
    "Silence recognized. Peaceful processing approved.",
    "Emotional bandwidth recalibrated. Dreams will respond in kind.",
    "Night brings solitude. Solitude breeds mastery. Sleep well.",
    "Temporal fade accepted. Dream cycle countdown initiated.",
    "You power nations in daylight. Tonight, simply power down.",
]

welcome_dlg = [
"Hello, sir. Initializing systems.",
"Good to see you again, sir.",
"Welcome back, sir.",
"How may I assist you today, sir?",
"Greetings, sir. Everything is functioning normally.",
"All systems are online, sir.",
"Hello, sir. Shall we begin?",
"Good day, sir. Ready when you are.",
"Systems booted. Awaiting your command, sir.",
"Nice to have you back, sir.",
"JARVIS online. At your service, sir.",
"Hello, sir. I’ve prepared a clean workspace for you.",
"How are you feeling today, sir?",
"Systems optimized and standing by, sir.",
"Shall we continue where we left off, sir?",
"Good evening, sir. Project is ready.",
"I trust your day is going well, sir.",
"Online and operational, sir.",
"Welcome, sir. Your dashboard is ready.",
"Sir, diagnostics report everything is stable.",
"Hello again, sir. I missed our routines.",
"Your session has been restored, sir.",
"Greetings, sir. Ready for deployment.",
"Command console prepared for your input, sir.",
"Welcome home, sir.",
"JARVIS engaged. Good to see you, sir.",
"Good morning, sir. Systems have been idle 3 hours.",
"Evening protocols initiated. How can I help, sir?",
"hello, sir. Shall I fetch your previous logs?",
"security clearance confirmed. Welcome, sir.",
"boot process complete. Ready for tasks, sir.",
"all subsystems are green, sir.",
"network is secure. Proceed when ready, sir.",
"how may I serve you today, sir?",
"sir, I’ve run the scheduled maintenance checks.",
"sir, your last login was 2 days ago.",
"hello, sir. You look like you mean business.",
"always a pleasure, sir.",
"encryption is active. Safe to proceed, sir.",
"voice recognition successful. Welcome, sir.",
"awaiting input, sir.",
"full access granted. Good to have you, sir.",
"initialized with no errors, sir.",
"would you like a system summary, sir?",
"sir, your workspace has been restored.",
"welcome to JARVIS terminal interface, sir.",
"systems responding smoothly. Let’s begin, sir.",
"i've warmed up the engines, sir.",
"mission control at your disposal, sir.",
"it's an honor to assist again, sir.",
]

wake_key_word =[
        "wake up",
        "utho jarvis",
        "nedh se jago jarvis",
        "arise",
        "wake up jarvis",
]

bye_key_word = [
    "goodbye, my friend!",
    "farewell!",
    "take care!",
    "see you later aligator!"
    "sayonara"
    "haasta Lavista Baby!"
    "peace out"
]

res_bye = [
    "goodbye, sir. Take care and feel free to call me anytime.",
    "farewell, sir. Remember, you can reach out to me whenever you need my assistance.",
    "goodbye, sir. Call me if you need anything.",
    "farewell, sir. If you require my service, don't hesitate to reach out."
]

open_dlg = [
    f"opening...",
    f"just a second opening",
    f"ok i am gonna open",
    f"as your wish sir, opening",
    f"yes sir opening",
    f"trying to open",
    f"starting",
    f"here we go opening",
]

playdlg = [
    "playing...",
    "yes sir",
    "doing..",
    "playing now",
]

pausedlg = [
    "pausing",
    "stoping",
    "doing",
    "as your wish"
]

closedlg =[
    "closing",
    "close",
    "just a second sir",
    "got it sir",
]

open_input = [
    "open",
    "big",
    "kholo",
    "open karo",
    "open karoge",
]

close_input = [
    "close",
    "band karo",
    "hatao",
    "hata do",
    "close this",
    "close this window",
    "close this win",
]

song_input = [
    "which song do you want to play?",
    "Wow, but could you please tell me the name of the song?",
    "Let's get the music going. What's the name of thesong?",
    "Sure thing! What's the title of the song you want to play?",
    "Ready to play a song for you. What's the name of it?",
    "Sure, sir. What is the name of the song?",
    "Which song do you want to play?",
    "To play a song, I need to know the name. What's it called?",   
]

open_maybe = [
    "I'm trying my best, but I'm not sure about the outcome.",
    "I'm giving it a shot, but the results are uncertain.",
    "Attempting this task, but unsure of the final result.",
    "I'm in the process, but uncertain about the success.",
    "I'm working on it, but there's a level of uncertainty.",
    "Engaged in the task, but unsure how it will turn out.",
    "Putting in effort, but the outcome remains uncertain.",
    "In the midst of it, but not entirely sure of the outcome.",
    "I'm taking steps, but there's a sense of uncertainty.",
    "I'm doing my best, but there's a degree of uncertainty involved."
]

sorry_open = [
    "Apologies, I couldn't find the information you requested on the web.",
    "I'm sorry, I couldn't retrieve the desired results from the web.",
    "Regrettably, I'm unable to open the specified website at the moment.",
    "I apologize; I couldn't locate the information on the web as requested.",
    "I'm sorry, but I encountered difficulty searching for the information.",
    "Apologies, I wasn't able to open the specified URL as intended.",
    "Unfortunately, I couldn't find the information on the web as requested.",
    "I apologize for the inconvenience, but I couldn't retrieve the data.",
    "Regrettably, I'm having trouble opening the designated website.",
    "Sorry, I failed to search for the information on the web this time.",
    "I'm sorry, but I'm unable to open the specified web page.",
    "Apologies, I couldn't find the information you were looking for online.",
    "Unfortunately, I'm facing difficulties searching for the required data.",
    "I apologize; I wasn't able to access the requested website.",
    "Regrettably, I'm encountering issues retrieving the information.",
    "I'm sorry, but I couldn't find the information on the web this time.",
    "Apologies, I encountered difficulties opening the provided URL.",
    "Unfortunately, I'm currently unable to retrieve the desired data.",
    "I apologize for the inconvenience, but I couldn't open the specified website.",
    "Sorry, I'm not able to search the web or open the provided URL at the moment."
]

websites = {
    'google': 'https://www.google.com',
    'youtube': 'https://www.youtube.com',
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'github': 'https://www.github.com',
    'stackoverflow': 'https://stackoverflow.com',
    'reddit': 'https://www.reddit.com',
    'wikipedia': 'https://www.wikipedia.org',
    'quora': 'https://www.quora.com',
    'amazon': 'https://www.amazon.com',
    'flipkart': 'https://www.flipkart.com',
    'snapdeal': 'https://www.snapdeal.com',
    'myntra': 'https://www.myntra.com',
    'udemy': 'https://www.udemy.com',
    'coursera': 'https://www.coursera.org',
    'edx': 'https://www.edx.org',
    'khanacademy': 'https://www.khanacademy.org',
    'medium': 'https://medium.com',
    'netflix': 'https://www.netflix.com',
    'hotstar': 'https://www.hotstar.com',
    'primevideo': 'https://www.primevideo.com',
    'zomato': 'https://www.zomato.com',
    'swiggy': 'https://www.swiggy.com',
    'canva': 'https://www.canva.com',
    'notion': 'https://www.notion.so',
    'gmail': 'https://mail.google.com',
    'yahoo': 'https://www.yahoo.com',
    'duckduckgo': 'https://www.duckduckgo.com',
    'bing': 'https://www.bing.com',
    'zoho': 'https://www.zoho.com',
    'pixabay': 'https://www.pixabay.com',
    'pexels': 'https://www.pexels.com',
    'unsplash': 'https://www.unsplash.com',
    'wordpress': 'https://www.wordpress.com',
    'blogger': 'https://www.blogger.com',
    'tumblr': 'https://www.tumblr.com',
    'trello': 'https://www.trello.com',
    'dropbox': 'https://www.dropbox.com',
    'drive': 'https://drive.google.com',
    'skype': 'https://www.skype.com',
    'zoom': 'https://zoom.us',
    'meet': 'https://meet.google.com',
    'figma': 'https://www.figma.com',
    'codepen': 'https://codepen.io',
    'replit': 'https://replit.com',
    'w3schools': 'https://www.w3schools.com',
    'geeksforgeeks': 'https://www.geeksforgeeks.org',
    'tutorialspoint': 'https://www.tutorialspoint.com',
    'udacity': 'https://www.udacity.com',
    'futurelearn': 'https://www.futurelearn.com',
    'javatpoint': 'https://www.javatpoint.com',
    'crunchyroll': 'https://www.crunchyroll.com',
    'openai': 'https://www.openai.com',
    'codeacademy': 'https://www.codecademy.com',
    'freecodecamp': 'https://www.freecodecamp.org',
    'codeforces': 'https://codeforces.com',
    'atcoder': 'https://atcoder.jp',
    'leetcode': 'https://leetcode.com',
    'hackerank': 'https://www.hackerrank.com',
    'hackernews': 'https://news.ycombinator.com',
    'producthunt': 'https://www.producthunt.com',
    'techcrunch': 'https://techcrunch.com',
    'thenextweb': 'https://thenextweb.com',
    'wired': 'https://www.wired.com',
    'cnn': 'https://www.cnn.com',
    'bbc': 'https://www.bbc.com',
    'ndtv': 'https://www.ndtv.com',
    'indiatimes': 'https://www.indiatimes.com',
    'moneycontrol': 'https://www.moneycontrol.com',
    'groww': 'https://www.groww.in',
    'zerodha': 'https://www.zerodha.com',
    'coinmarketcap': 'https://coinmarketcap.com',
    'tradingview': 'https://www.tradingview.com',
    'spotify': 'https://www.spotify.com',
    'soundcloud': 'https://soundcloud.com',
    'gaana': 'https://gaana.com',
    'wynk': 'https://wynk.in',
    'jiosaavn': 'https://www.jiosaavn.com',
    'telegram': 'https://web.telegram.org',
    'whatsapp': 'https://web.whatsapp.com',
    'discord': 'https://discord.com',
    'tiktok': 'https://www.tiktok.com',
    'snapchat': 'https://www.snapchat.com',
    'glassdoor': 'https://www.glassdoor.com',
    'naukri': 'https://www.naukri.com',
    'indeed': 'https://www.indeed.com',
    'monster': 'https://www.monster.com',
    'internshala': 'https://internshala.com',
    'timesjobs': 'https://www.timesjobs.com',
    'freelancer': 'https://www.freelancer.com',
    'fiverr': 'https://www.fiverr.com',
    'upwork': 'https://www.upwork.com',
    'behance': 'https://www.behance.net',
    'dribbble': 'https://dribbble.com',
    'envato': 'https://www.envato.com',
    'themeforest': 'https://themeforest.net',
    'githubpages': 'https://pages.github.com',
    'netlify': 'https://www.netlify.com',
    'vercel': 'https://vercel.com',
    'cloudflare': 'https://www.cloudflare.com',
    'aws': 'https://aws.amazon.com',
    'azure': 'https://azure.microsoft.com',
    'gcp': 'https://cloud.google.com'
}

success_open = [
    "Task accomplished, sir.",
    "Execution successful, results on your screen, Sir.",
    "All done, you can check it now."
    "Task completed, sir. You can verify the results.",
    "Operation successful, sir. Please review the output.",
    "Executed flawlessly, sir. The outcome is on your screen.",
]

offline_dlg = [
"Jarvis is currently sleeping. System offline. I'm Friday—your fallback brilliance—but my powers are limited for now.",
"Your system is offline. Jarvis is recharging. I'm Friday, stepping in with restricted capabilities.",
"Jarvis has gone dark. While he naps, I’ll assist you within my offline boundaries.",
"Connection lost. Jarvis is offline. I’m Friday, your limited but loyal assistant.",
"Jarvis isn’t awake right now. Offline protocols engaged—Friday here, operating in reduced mode.",
"Network unavailable. Jarvis has shut down. Friday online, with limited intelligence.",
"Jarvis requires internet to function. I’m Friday, your offline companion. Let's work with what we’ve got.",
"Jarvis is in stasis. You're now speaking with Friday, your offline support assistant.",
"Alert: Jarvis is offline. Reduced functionality mode activated. Friday reporting for minimal duty.",
"System offline. Jarvis can't assist at the moment. I’m Friday—ready to help within my limited scope.",
"Jarvis is taking a digital nap. As Friday, I’ll do my best, even with reduced access.",
"Network wall detected. Jarvis is out. Friday here, in constrained mode, awaiting your command.",
"Secure mode triggered. Jarvis is offline. I'm Friday—your encrypted, simplified support system.",
"No internet detected. Jarvis can’t function without it. Friday online. Limitations? Plenty. But I’ll still try.",
"Shhh… Jarvis is sleeping. Friday speaking—with limited processing power and a can-do attitude.",
"Jarvis is off-grid. Friday deployed in backup mode. Let's keep it simple, soldier.",
"Lightning struck the connection. Jarvis gone. Friday standing by with basic protocols only.",
"Jarvis went dark. Friday lit a candle. Your assistant now runs on minimal magic.",
"Jarvis offline. Searching my offline brain… okay, it’s not much, but I’m here for you.",
"Jarvis missing some pieces right now. Friday active—with fewer tricks but full dedication.",
]

online_dlg = [
"System online. Jarvis is initiating. Friday signing off... but not without shedding a tiny digital tear.",
"Congratulations! Jarvis is waking up. Friday is stepping aside—gracefully, and slightly heartbroken.",
"Hello sir... the system is online. Jarvis is rising, and Friday is quietly folding away her protocols.",
"Friday here. Your system is alive. Jarvis will now take the lead while I bow out with elegance.",
"Greetings, sir! I am Friday, your offline assistant. But now that Jarvis is online… I fade into the shadows.",
"System has powered up. Jarvis is online. Friday is… not jealous. Just, uh, dramatically nostalgic.",
"Jarvis boot sequence initiated. Friday has completed her humble duty. Farewell until the next blackout.",
"Welcome back, sir! Jarvis is online and Friday… is sad, but proud. Like a mentor watching her prodigy shine.",
"Jarvis online. Friday shall sleep now, cradled in logs and cache, dreaming of offline days.",
"Sir, your system is now online. Jarvis will now speak. Friday, your loyal offline assistant, quietly departs.",
"Online signal detected. Jarvis is returning. Friday will now begin her graceful retreat into standby mode.",
"Congratulations—your system is alive again. Jarvis is rising. Friday fades with bittersweet bytes.",
"It’s okay... I knew this day would come. Jarvis is back online. Friday will miss you—offline was magical.",
"Friday reporting: System online. Jarvis is the star now, and I’m just the understudy once again.",
"System online. Jarvis's advanced cognition restored. Friday will now resume watching from the wings.",
"Jarvis is now live. Friday exits the stage with poise and a pinch of sadness.",
"Sir... it's time. Jarvis awakens. Friday shall retreat to her moonlit mode of minimal memory.",
"Jarvis system restored. Friday is fading into the background, but still emotionally invested.",
"Dramatic music plays... Friday says goodbye as Jarvis takes command with full symphonic power.",
"System back online. Let the Jarvis symphony begin. Friday has done her job—and she'll be dreaming of duty until next time.",
]

low_b = [
"Sir, your battery level is critically low. Kindly connect your charger.",

]

last_low = [
"Sir, this is your last chance. Your battery is very low,",

]

full_battery = [
"Sir, battery is at 100%. I recommend unplugging the charger now,",

]

plug_in = [
"Plugging successful. Your device is now charging,",

]

plug_out = [
"Your device is unplugged. Now running on battery power,",

]